.repos/nexmo-community/nexmo-dotnet-quickstart/NexmoDotNetQuickStarts/Controllers/SMSController.cs
using Nexmo.Api;
using System.Diagnostics;
using System.Web.Http;
using System.Web.Mvc;

namespace NexmoDotNetQuickStarts.Controllers
{
    // For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

    public class SMSController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        [System.Web.Mvc.HttpGet]
        public ActionResult Send()
        {
            return View();
        }

        [System.Web.Mvc.HttpPost]
        public ActionResult Send(string to, string text)
        {
            var TO_NUMBER = to;

            var client = new Client(creds: new Nexmo.Api.Request.Credentials
            {
                ApiKey = "NEXMO_API_KEY",
                ApiSecret = "NEXMO_API_SECRET"
            });

            var results = client.SMS.Send(request: new SMS.SMSRequest
            {
                from = "Acme Inc",
                to = TO_NUMBER,
                text = "A test SMS sent using the Nexmo SMS API"
            });
            return View("Index");
        }

        [System.Web.Mvc.HttpGet]
        public ActionResult Receive([FromUri]SMS.SMSInbound response)
        {

            if (null != response.to && null != response.msisdn)
            {
                Debug.WriteLine("------------------------------------");
                Debug.WriteLine("INCOMING TEXT");
                Debug.WriteLine("From: " + response.msisdn);
                Debug.WriteLine(" Message: " + response.text);
                Debug.WriteLine("------------------------------------");
                return new HttpStatusCodeResult(200);

            }
            else
            {
                Debug.WriteLine("------------------------------------");
                Debug.WriteLine("Endpoint was hit.");
                Debug.WriteLine("------------------------------------");
                return new HttpStatusCodeResult(200);

            }

        }

        [System.Web.Mvc.HttpGet]
        public ActionResult DLR([FromUri]SMS.SMSDeliveryReceipt response)
        {

            Debug.WriteLine("------------------------------------");
            Debug.WriteLine("DELIVERY RECIEPT");
            Debug.WriteLine("Message ID: " + response.messageId);
            Debug.WriteLine("From: " + response.msisdn);
            Debug.WriteLine("To: " + response.to);
            Debug.WriteLine("Status: " + response.status);
            Debug.WriteLine("------------------------------------");

            return new HttpStatusCodeResult(200);
        }

    }

}

.repos/nexmo-community/nexmo-dotnet-quickstart/NexmoDotNetQuickStarts/Views/SMS/Send.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@using (Html.BeginForm("Send", "SMS", FormMethod.Post))
{
    <br />
    <input type="text" name="to" id="to" placeholder="To" />
    <input type="text" name="text" id="text" placeholder="Text" />
    <input type="submit" value="Send" />
}

.repos/nexmo-community/nexmo-dotnet-quickstart/NexmoDotNetQuickStarts/Views/SMS/index.cshtml
<div>
    <h1>SMS</h1>
    <hr style="height:2px;border:none;color:#333;background-color:black" />
    <h2>@Html.ActionLink("Send", "Send", "SMS")</h2>
    <h2>Receive - Check Debug Log for Incoming Texts</h2>
    <h2>Delivery Receipt - Check Debug Log for Delivery Receipts</h2>
</div>