.repos/nexmo-community/nexmo-dotnet-quickstart/NexmoVoiceASPNetCoreQuickStarts/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace NexmoVoiceASPNetCoreQuickStarts.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

.repos/nexmo-community/nexmo-dotnet-quickstart/NexmoVoiceASPNetCoreQuickStarts/Controllers/VoiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Nexmo.Api;
using Nexmo.Api.Voice;
using NexmoVoiceASPNetCoreQuickStarts.Helpers;
using Microsoft.AspNetCore.Hosting;
using System.Web;

namespace NexmoVoiceASPNetCoreQuickStarts.Controllers
{
    public class VoiceController : Controller
    {
        private readonly IHostingEnvironment _hostingEnvironment;
        private NCCOHelpers _nccohelper;

        public VoiceController(IHostingEnvironment hostingEnvironment)
        {
            _hostingEnvironment = hostingEnvironment;
            _nccohelper = new NCCOHelpers();
            
        }
        public IActionResult Index()
        {
            ViewData["NCCOButtonText"] = "Create NCCO";
            return View();
        }

        [HttpGet]
        public ActionResult MakeTextToSpeechCall()
        {
            return View();
        }

        [HttpPost]
        public ActionResult MakeTextToSpeechCall(string to)
        {
            var NEXMO_FROM_NUMBER = Configuration.Instance.Settings["appsettings:NEXMO_FROM_NUMBER"];
            var NEXMO_TO_NUMBER = to;
            var NEXMO_CALL_ANSWER_URL = "https://raw.githubusercontent.com/nexmo-community/ncco-examples/gh-pages/first_call_talk.json";

            var results = Call.Do(new Call.CallCommand
            {
                to = new[]
                {
                    new Call.Endpoint {
                        type = "phone",
                        number = NEXMO_TO_NUMBER
                    }
                },
                from = new Call.Endpoint
                {
                    type = "phone",
                    number = NEXMO_FROM_NUMBER
                },
                answer_url = new[]
                {
                    NEXMO_CALL_ANSWER_URL
                }
            });

            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public ActionResult PlayAudioToCaller()
        {
            return View();
        }

        [HttpPost]
        public ActionResult PlayAudioToCaller(string to)
        {
            var NEXMO_FROM_NUMBER = Configuration.Instance.Settings["appsettings:NEXMO_FROM_NUMBER"];
            var NEXMO_TO_NUMBER = to;
            var NEXMO_CALL_ANSWER_URL = "https://raw.githubusercontent.com/nexmo-community/ncco-examples/gh-pages/first_call_speech.json";

            var results = Call.Do(new Call.CallCommand
            {
                to = new[]
                {
                    new Call.Endpoint {
                        type = "phone",
                        number = NEXMO_TO_NUMBER
                    }
                },
                from = new Call.Endpoint
                {
                    type = "phone",
                    number = NEXMO_FROM_NUMBER
                },
                answer_url = new[]
                {
                    NEXMO_CALL_ANSWER_URL
                }
            });

            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public ActionResult CreateTalkNCCO(string text, string voiceName)
        {
            _nccohelper.CreateTalkNCCO(_hostingEnvironment.WebRootPath, text, voiceName);

            ViewData["NCCOButtonText"] = "NCCO Created";
            return View("MakeTextToSpeechCall");
        }

        [HttpPost]
        public ActionResult CreateStreamNCCO(string[] streamUrl, int level=0, bool bargeIN = false, int loop =1)
        {
            _nccohelper.CreateStreamNCCO(_hostingEnvironment.WebRootPath, streamUrl, level, bargeIN, loop);

            ViewData["NCCOButtonText"] = "NCCO Created";
            return View("PlayAudioToCaller");
        }
    }
}

.repos/nexmo-community/nexmo-dotnet-quickstart/NexmoVoiceASPNetCoreQuickStarts/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>

<p>The Nexmo Voice API is the easiest way to build high-quality voice applications in the Cloud. With the Voice API you:

    <ul>
        <li>Build apps that scale with the web technologies that you are already using</li>
        <li>Control the flow of inbound and outbound calls in JSON with Nexmo Call Control Objects (NCCO)</li>
        <li>Record and store inbound or outbound calls</li>
        <li>Create conference calls</li>
        <li>Send text-to-speech messages in 23 languages with different genders and accents</li>
    </ul>
    </p>

.repos/nexmo-community/nexmo-dotnet-quickstart/NexmoVoiceASPNetCoreQuickStarts/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>

<address>
    Nexmo Ltd<br />
    Idt House, 38-, 44 Featherstone St, London EC1Y 8RN<br />
    <abbr title="Phone"></abbr>
    020 7490 2866
</address>

<address>
    <strong>Developer relations team:</strong> <a href="mailto:devrel@nexmo.com">devrel@nexmo.com</a><br />
</address>

.repos/nexmo-community/nexmo-dotnet-quickstart/NexmoVoiceASPNetCoreQuickStarts/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/text-to-speech-asp.png" alt="" class="img-responsive" />
            @*<div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>*@
        </div>
        <div class="item">
            <img src="~/images/text-to-speech-asp.png" alt="" class="img-responsive" />
            @*<div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>*@
        </div>
        <div class="item">
            <img src="~/images/text-to-speech-asp.png" alt="" class="img-responsive" />
            @*<div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>*@
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a >@Html.ActionLink("Make a text-to-speech phone call", "MakeTextToSpeechCall", "Voice")</a></li>
            <li><a>@Html.ActionLink("Play audio to a caller", "PlayAudioToCaller", "Voice")</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Concepts</h2>
        <ul>
            <li><a href="https://developer.nexmo.com/voice/voice-api/overview" target="_blank">Nexmo Voice API</a></li>
            <li><a href="https://developer.nexmo.com/concepts/guides/applications" target="_blank">Nexmo Application</a></li>
            <li><a href="https://developer.nexmo.com/tools" target="_blank">CLI</a></li>
            <li><a href="https://developer.nexmo.com/voice/voice-api/guides/ncco" target="_blank">NCCO</a></li>
        </ul>
    </div>
</div>